PL_MVC/Controllers/EmpresaController.cs
using Aspose.Cells;
using ML;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity.Core.Common.CommandTrees.ExpressionBuilder;
using System.Data.OleDb;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class EmpresaController : Controller
    {


        //public ActionResult GetAll()
        //{
        //    ML.Result resultSubCategoria = new ML.Result();
        //    resultSubCategoria.Objects = new List<Object>();

        //    using (var client = new HttpClient())
        //    {
        //        client.BaseAddress = new Uri("http://localhost:40840/api/");

        //        var responseTask = client.GetAsync("usuario/" + idUsuario);
        //        responseTask.Wait();

        //        var result = responseTask.Result;

        //        if (result.IsSuccessStatusCode)
        //        {
        //            var readTask = result.Content.ReadAsAsync<ML.Result>();
        //            readTask.Wait();

        //            foreach (var resultItem in readTask.Result.Objects)
        //            {
        //                ML.SubCategoria resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.SubCategoria>(resultItem.ToString());
        //                resultSubCategoria.Objects.Add(resultItemList);
        //            }
        //        }
        //    }
        //    return View(resultSubCategoria);
        //}




        // GET: Empresa
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Result result = new ML.Result();
            result.Objects = new List<object>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(ConfigurationManager.AppSettings["url"]);
                var responseTask = client.GetAsync("empresa/getall");
                    responseTask.Wait();

                      var  resultado = responseTask.Result;

                if (resultado.IsSuccessStatusCode)
                {
                    var readTask = resultado.Content.ReadAsAsync<ML.Result>();
                    readTask.Wait();

                    foreach (var resultItem in readTask.Result.Objects)
                    {
                        ML.Empresa resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Empresa>(resultItem.ToString());
                        result.Objects.Add(resultItemList);
                    }
                }




            }




            //aqui empieza el antiguo codigo del gelall
            //ML.Empresa empresa = new ML.Empresa();
            //empresa.Empresas = new List<object>();
            //EmpresaServices.EmpresaClient servicio = new EmpresaServices.EmpresaClient();
            //ML.Result result = servicio.EmpresaGetAll();

            //// ML.Result result = BL.Empresa.EmpresaGetAll();
            //if (result.Correct)
            //{
            //    empresa.Empresas = result.Objects;
            //}
            //else
            //{
            //    ViewBag.Message = result.ErrorMessage;

            //}

            //ViewBag.Title = "Empresas";

            ML.Empresa empresa = new ML.Empresa();
            empresa.Empresas = result.Objects;

            return View(empresa);






        }


        //el form pero de la empresa 
        [HttpGet]
        public ActionResult Form(int? IdEmpresa)

        {



            ML.Empresa empresa = new ML.Empresa();
            //usuario.Rol = new ML.Rol();
            //ML.Result result = BL.Rol.GetAllEF();
            //usuario.Rol.Roles = resultRol.Objects;

            if (IdEmpresa == null)

            {
                ViewBag.Accion = "Agregar Empresa";
            }

            else

            {


                ML.Result result = new ML.Result();
                try
                {
                    string urlAPI = System.Configuration.ConfigurationManager.AppSettings["url"];
                    using (var client = new HttpClient())
                    {
                        client.BaseAddress = new Uri(urlAPI);//"api/empresa/getbyid/{IdEmpresa}"
                        var responseTask = client.GetAsync("empresa/getbyid/" + IdEmpresa);
                        responseTask.Wait();
                        var resultAPI = responseTask.Result;
                        if (resultAPI.IsSuccessStatusCode)
                        {
                            var readTask = resultAPI.Content.ReadAsAsync<ML.Result>();
                            readTask.Wait();
                            ML.Empresa resultItemList = new ML.Empresa();
                            resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Empresa>(readTask.Result.Object.ToString());
                            result.Object = resultItemList;

                            result.Correct = true;
                        }
                        else
                        {
                            result.Correct = false;
                            result.ErrorMessage = "No existen registros en la tabla Departamento";
                        }

                    }
                }

                catch (Exception ex)
                {
                    result.Correct = false;
                    result.ErrorMessage = ex.Message;

                }
                empresa = (ML.Empresa)result.Object;
                //return View(empresa);
            }
            //empresa.IdEmpresa = IdEmpresa;

            //EmpresaServices.EmpresaClient servicio = new EmpresaServices.EmpresaClient();
            //ML.Result result = servicio.EmpresaGetById(empresa);

            ////ML.Result result = BL.Empresa.EmpresaGetById(empresa);

            //if (result.Correct)
            //{
            //    empresa = (ML.Empresa)result.Object;
            //}

            //// usuario.Rol.Roles = resultRol.Objects;

            ////BL.Usuario.UpdateLINQ(usuario);
            //ViewBag.Accion = "Actualizar datos";



        
            return View(empresa);
        }

        [HttpPost]


        public ActionResult Form(ML.Empresa empresa)

        {
            ML.Result result = new ML.Result();

            if (empresa.IdEmpresa == null)

            {


                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(ConfigurationManager.AppSettings["url"]);

                    //HTTP POST
                    var postTask = client.PostAsJsonAsync<ML.Empresa>("empresa/add", empresa);
                    postTask.Wait();

                    var resultado = postTask.Result;
                    if (resultado.IsSuccessStatusCode)
                    {

                        ViewBag.Mesaje = "Agregado correctamente";
                        return View("Modal");
                        //return RedirectToAction("GetAll");
                    }
                    else
                    {
                        ViewBag.Mesaje = "No fue agregado correctamente";
                        return View("Modal");
                    }
                }

                //return View("GetAll");
                /* if (fuImagen != null)
                 {
                     usuario.Imagen = convertFileToByteArray(fuImagen);
                 }*/


                // DepartamentoService.DepartamentoClient departamentoClient = new DepartamentoService.DepartamentoClient();
                // var result = departamentoClient.GetAll();

                // aqui empieaza en antiguo
                // EmpresaSoap.EmpresaClient emp = new EmpresaSoap.EmpresaClient();
                // result = emp.EmpresaAdd(empresa);
                // //se tiene que cachar el resultado del result 
                //// result = BL.Empresa.EmpresaAdd(empresa);
                // //return View(usuario);

                // if (result.Correct)
                // {
                //     ViewBag.Mensaje = result.ErrorMessage;
                //     //ViewBag.Mesaje = "prueba";
                //     return View("Modal");
                // }
                // else
                // {
                //     return View();
                // }



            }

            else

            {


                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(ConfigurationManager.AppSettings["url"]);

                    //HTTP POST
                    //var postTask = client.PostAsJsonAsync<ML.SubCategoria>("subcategoria/update", subcategoria);
                    var putTask = client.PutAsJsonAsync<ML.Empresa>("empresa/update" , empresa);
                    putTask.Wait();

                    var resultado = putTask.Result;
                    if (resultado.IsSuccessStatusCode)
                    {
                        ViewBag.Mensaje = "empresa actualizada correctamente";
                        return View("Modal");
                    }
                }

                return View("Modal");

            }
            //aqui empieza el codigo antiguo 
            /*  if (fuImagen != null)
              {
                  usuario.Imagen = convertFileToByteArray(fuImagen);
              }*/
            // EmpresaSoap2.EmpresaClient emp = new EmpresaSoap2.EmpresaClient();
            // result = emp.EmpresaUpdate(empresa);
            //// result = BL.Empresa.EmpresaUpdate(empresa);
            // if (result.Correct)
            // {
            //     ViewBag.Mensaje = result.ErrorMessage;
            //     return View("Modal");
            // }
            // else { return View(); }



        

        }

        //[HttpDelete]
        public ActionResult Delete(int IdEmpresa)
        {
            //se
            ML.Result resultado = new ML.Result();
            
            using (var client = new HttpClient())
            {

PL_MVC/Views/Empresa/CargaMasivaEmpresa.cshtml
@model ML.Empresa
@{
    ViewBag.Title = "CargaMasiva";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CargaMasiva</h2>
<div class="container">
    <h1>Carga Masiva de Empresas</h1>
    <h5>Seleccione con que tipo de archivo desea hacer la carga</h5>
    <hr />

    <div class="row">
        <div class="col-md-6">
            <a><input type="submit" value="Excel" class="btn btn-success col-md-12" id="xlsx" /></a>
        </div>
        <div class="col-md-6">
            <a><input type="submit" value="TXT" class="btn btn-primary col-md-12" id="txt" /></a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            @using (Html.BeginForm("CargaMasivaEmpresa", "Empresa", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @*<input type="file" id="archivo" name="archivo" />

                    <button class="btn btn-success" type="submit">
                        Carga Masiva
                    </button>*@

                <div class="row g-3" id="fuImage" style="display:none;">
                    <div class="col-md-6">
                        <div class="input-group">
                            <span class="input-group-text" id="basic-addon1"><i class="bi bi-file-earmark-text-fill" style="color: lightseagreen"></i></span>
                            <input type='file' class="form-control" name="excel" />
                        </div>
                    </div>
                    @if (Model.isValidExcel)
                        {
                    <div class="row g-3">
                        <div class="col-md-1">
                            <a><input type="submit" value="Insertar" class="btn btn-success" /></a>
                            <br />
                        </div>
                    </div>
                    }
                        else
                        {
                    <div class="row g-3">
                        <div class="col-md-1">
                            <a><input type="submit" value="Validar" class="btn btn-success" /></a>
                            <br />
                        </div>
                    </div>
                     } 
                </div>
                <br />

            }
        </div>
        <div class="col-md-6">

            @using (Html.BeginForm("CargaMasiva", "Empresa", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @*<input type="file" id="archivo" name="archivo" />

                    <button class="btn btn-success" type="submit">
                        Carga Masiva
                    </button>*@

                <div class="row g-3" id="fuImage2" style="display:none;">
                    <div class="col-md-6">
                        <div class="input-group">
                            <span class="input-group-text" id="basic-addon1"><i class="bi bi-file-earmark-text-fill" style="color: lightseagreen"></i></span>
                            <input type='file' class="form-control" name="excel" />
                        </div>
                    </div>
                    @if (Model.isValidExcel)
                        {
                    <div class="row g-3">
                        <div class="col-md-1">
                            <a><input type="submit" value="Insertar" class="btn btn-info" /></a>
                            <br />
                        </div>
                    </div>
                    }
                        else
                        {
                    <div class="row g-3">
                        <div class="col-md-1">
                            <a><input type="submit" value="Validar" class="btn btn-info" /></a>
                            <br />
                        </div>
                    </div>
                     } 
                </div>
                <br />

            }

        </div>
    </div>

    <table class="table table-bordered table-responsive">
        <thead>
            <tr>


                <td>Nombre</td>
                <td>Telefono</td>
                <td>Email</td>
                <td>DireccionWeb</td>
                <td>Errores</td>
                <td>Es valido</td>

            </tr>
        </thead>


        <tbody>
            @foreach (ML.Empresa empresa in Model.Empresas)
            {
                <tr>


                    <td>@empresa.Nombre</td>
                    <td>@empresa.Telefono</td>
                    <td>@empresa.DireccionWeb</td>
                    <td>@empresa.Email</td>
                    <td>@empresa.ErrorMessage</td>
                    @if (empresa.isValidExcel)
                    {
                        <td style="text-align: center; vertical-align: middle;">
                           <i style = "color:green;" class="bi bi-check-square-fill"></i>
                        </td>
                    }
                    else
                    {
                        <td style="text-align: center; vertical-align: middle;">
                            <i style = "color:red;" class="bi bi-x-square-fill"></i>
                        </td>
                    }


                </tr>
            }
        </tbody>
    </table>

</div>





    @Scripts.Render("~/bundles/jquery")
    <script type="text/javascript">


        $('#xlsx').click(function () {
            $('#fuImage').toggle('slow', function () {
            });
        });


        $('#txt').click(function () {
            $('#fuImage2').toggle('slow', function () {
            });
        });
    </script>

PL_MVC/Views/Empresa/Form.cshtml
@model ML.Empresa
@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View</h2>

<div class="container">

    <div class="row">
        <div class="col-md-12">
            <h5>Ingrese la informacion solicitada</h5>
            <hr />
        </div>
    </div>

    @using (Html.BeginForm("Form", "Empresa", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="row">
            <div class="col-md-6 visually-hidden">
                @Html.LabelFor(model => model.IdEmpresa)
                @Html.TextBoxFor(model => model.IdEmpresa, new { @class = "form-control" })
            </div>

            <div class="col-md-6">
                @Html.LabelFor(model => model.Nombre)
                @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control" })
            </div>

            <div class="col-md-6">
                @Html.LabelFor(model => model.Email)
                @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
            </div>

        </div>





        <div class="row">
            <div class="col-md-6">
                @Html.LabelFor(model => model.Telefono)
                @Html.TextBoxFor(model => model.Telefono, new { @class = "form-control" })
            </div>

            <div class="col-md-6">
                @Html.LabelFor(model => model.DireccionWeb)
                @Html.TextBoxFor(model => model.DireccionWeb, new { @class = "form-control" })
            </div>



        </div>



        





        <button class="btn btn-success" type="submit">
            Guardar
        </button>






    }

</div>

PL_MVC/Views/Empresa/GetAll.cshtml
@model ML.Empresa
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Empresa</h2>



<div class="row">
    <div class="col-md-12">
        <h5>Seleccione una para editarla o + para agregar...</h5>
        <hr />
    </div>
</div>

<div class="row">
    <div class="col-auto">


        @Html.ActionLink(" Agregar", "Form", "Empresa",new { area = "" } ,new { @class = "btn btn-success bi bi-person-plus" })


    </div>
</div>


<br />

<table class="table table-bordered table-responsive">
    <thead>
        <tr>
            <td>Editar</td>
            <td class="hidden">IdEmpresa</td>
            <td>Nombre</td>
            <td>Telefono</td>
            <td>Email</td>
            <td>DireccionWeb</td>
            <td>Eliminar</td>
        </tr>
    </thead>


    <tbody>
        @foreach (ML.Empresa empresa in Model.Empresas)
        {
            <tr>
                <td><a class="btn btn-warning bi bi-pencil" href="@Url.Action("Form", "Empresa", new { IdEmpresa = empresa.IdEmpresa })"></a></td>
                <td class="hidden">@empresa.IdEmpresa</td>
                <td>@empresa.Nombre</td>
                <td>@empresa.Telefono</td>
                <td>@empresa.Email</td>
                <td>@empresa.DireccionWeb</td>


                <td><a class="btn btn-danger bi bi-trash" href="@Url.Action("Delete", "Empresa", new { IdEmpresa= empresa.IdEmpresa})" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a></td>
            </tr>
        }
    </tbody>
</table>

PL_MVC/Views/Empresa/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">


<div class="modal fade" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Aviso</h4>
            </div>
            <div class="modal-body">
                <p>@ViewBag.Mensaje</p>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "CargaMasivaEmpresa", "Empresa", new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal('show');
</script>