PL_MVC/Controllers/DependienteController.cs
using System;   
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class DependienteController : Controller
    {
        // GET: Dependiente
        [HttpGet]
        public ActionResult GetAll()
        {

            ML.Empleado empleado = new ML.Empleado();
            empleado.Empleados = new List<object>();
            ML.Result result = BL.Empleado.EmpleadoGetAll();
            if (result.Correct)
            {
                empleado.Empleados = result.Objects;
            }
            else
            {
                ViewBag.Message = result.ErrorMessage;

            }

            ViewBag.Title = "Empresas";

            return View(empleado);

        }

        [HttpGet]

        public ActionResult GetByNumeroEmpleado(string numeroEmpleado)
        {
            ML.Dependiente dependiente = new ML.Dependiente();



            ML.Result result = BL.Dependiente.DependienteGetByNumeroEmpleado(numeroEmpleado);
            ML.Empleado empleado = new ML.Empleado();
            empleado.NumeroEmpleado = numeroEmpleado;
            ML.Result resultEmpleado = BL.Empleado.EmpleadoGetById(empleado);
            
            empleado = (ML.Empleado)resultEmpleado.Object;
            dependiente.Empleado = new ML.Empleado();
            dependiente.Empleado = empleado;
            Session["Empleado"] = numeroEmpleado;
            Session["NombreEmpleado"] = empleado.Nombre;
            if (result.Correct)
            {
                dependiente.Dependientes = result.Objects;
            }
            else
            {
                ViewBag.Message = result.ErrorMessage;

            }
            return View(dependiente);
        }
        [HttpGet]
        public ActionResult FormDependiente(int? idDependiente)
        {
            ML.Dependiente dependiente = new ML.Dependiente();

            ML.Result resultTipos = BL.DependienteTipo.DependienteTipoGetAll();
            dependiente.DependienteTipo = new ML.DependienteTipo();
            dependiente.DependienteTipo.DependienteTipos = resultTipos.Objects;
            dependiente.Empleado = new ML.Empleado();

            dependiente.Empleado.NumeroEmpleado = Session["Empleado"].ToString();
            //dependiente.Empleado.Nombre = Session["NombreEmpleado"].ToString();



            if (idDependiente == null)

            {
                
                ViewBag.Accion = "Agregar Usuario";
            }

            else

            {
                
                ML.Result result = BL.Dependiente.DependienteGetById(idDependiente.Value);

                if (result.Correct)
                {
                    dependiente = (ML.Dependiente)result.Object;
                    //ML.Dependiente dependiente1 = new ML.Dependiente();
                    //dependiente1.DependienteTipo = new ML.DependienteTipo();
                   // dependiente1 = (ML.Dependiente)result.Object;
                    //dependiente.DependienteTipo = new ML.DependienteTipo();
                    dependiente.DependienteTipo.DependienteTipos = resultTipos.Objects;
                   // dependiente.DependienteTipo.IdDependienteTipo = dependiente1.DependienteTipo.IdDependienteTipo;
                }
            }




                return View(dependiente);
        }

        [HttpPost]

        public ActionResult FormDependiente(ML.Dependiente dependiente)
        {

            ML.Result result = new ML.Result();

            if (dependiente.IdDependiente == 0)
            {
                result = BL.Dependiente.DependienteAdd(dependiente);
                ViewBag.Mensaje = result.ErrorMessage;

                return View("Modal");
            }
            else
            {
                result = BL.Dependiente.DependienteUpdate(dependiente);
                ViewBag.Mensaje = result.ErrorMessage;

                return View("Modal");


            }

        }

        public ActionResult Delete(int idDependiente)
        {
          
            
            ML.Result result = new ML.Result();
            result = BL.Dependiente.DependienteDelete(idDependiente); ViewBag.Mensaje = result.ErrorMessage;
            ViewBag.Mensaje = result.ErrorMessage;




            return View("Modal");
        }







        //    result = BL.Empleado.EmpleadoAdd(empleado);
        //    //return View(usuario);

        //    if (result.Correct)
        //    {
        //        ViewBag.Mensaje = result.ErrorMessage;
        //        //ViewBag.Mesaje = "prueba";
        //        return View("Modal");
        //    }
        //    else
        //    {
        //        return View("Modal");
        //    }
        //}
        //else
        //{
        //    if (fuImagen != null)
        //    {
        //        empleado.Foto = convertFileToByteArray(fuImagen);
        //    }


        //    result = BL.Empleado.EmpleadoUpdate(empleado);
        //    //return View(usuario);

        //    if (result.Correct)
        //    {
        //        ViewBag.Mensaje = result.ErrorMessage;
        //        //ViewBag.Mesaje = "prueba";
        //        return View("Modal");
        //    }
        //    else
        //    {
        //        return View("Modal");
        //    }
    }
}

PL_MVC/Views/Dependiente/FormDependiente.cshtml
@model ML.Dependiente

@{
    ViewBag.Title = "FormDependiente";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>FormDependiente</h2>


@using (Html.BeginForm("FormDependiente", "Dependiente", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="row">




        <div class="col-md-6 visually-hidden">
            @Html.LabelFor(model => model.Empleado.NumeroEmpleado)
            @Html.TextBoxFor(model => model.Empleado.NumeroEmpleado, new { @class = "form-control" })


        </div>


        <div class="col-md-6 visually-hidden">
            @Html.LabelFor(model => model.IdDependiente)
            @Html.TextBoxFor(model => model.IdDependiente, new { @class = "form-control" })


        </div>

        <div class="col-md-6">
            @Html.LabelFor(model => model.RFC)
            @Html.TextBoxFor(model => model.RFC, new { @class = "form-control" })
        </div>

    </div>

    <div class="row">

        <div class="col-md-6">
            @Html.LabelFor(model => model.Nombre)
            @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control" })
        </div>

        <div class="col-md-6">
            @Html.LabelFor(model => model.ApellidoPaterno)
            @Html.TextBoxFor(model => model.ApellidoPaterno, new { @class = "form-control" })
        </div>

        <div class="col-md-6">
            @Html.LabelFor(model => model.EstadoCivil)
            @Html.TextBoxFor(model => model.EstadoCivil, new { @class = "form-control" })
        </div>

        <div class="col-md-6">
            @Html.LabelFor(model => model.Genero)
            @Html.TextBoxFor(model => model.Genero, new { @class = "form-control" })
        </div>


    </div>

    <div class="row">
         <div class="col-md-6 visually-hidden">
     @Html.LabelFor(model => model.Empleado.NumeroEmpleado)
     @Html.TextBoxFor(model => model.Empleado.NumeroEmpleado, new { @class = "form-control" })


 </div>





    </div>





    <div class="row">

        <div class="col-md-6">
            @Html.LabelFor(model => model.ApellidoMaterno)
            @Html.TextBoxFor(model => model.ApellidoMaterno, new { @class = "form-control" })
        </div>




    </div>

    <div class="row">

        <div class="col-md-6">
            @Html.LabelFor(model => model.Telefono)
            @Html.TextBoxFor(model => model.Telefono, new { @class = "form-control" })
        </div>

        <div class="col-md-6">
            @Html.LabelFor(model => model.FechaNacimiento)
            @Html.TextBoxFor(model => model.FechaNacimiento, new { @class = "form-control", @id = "datepicker", @type = "text" })
            @Html.ValidationMessageFor(model => model.FechaNacimiento)
        </div>


    </div>

    <div class="row">


        <div class="col-md-4">
            @*comienza menu desplegable**@
            @Html.DropDownListFor(model => model.DependienteTipo.IdDependienteTipo, new SelectList(Model.DependienteTipo.DependienteTipos, "IdDependienteTipo", "Nombre"), "Seleccione una opción", new { @class = "form-control" })


            @* termina menu desplegable esto se llama html helper **@
        </div>

    </div>


    <div class="row">


    </div>

    <button class="btn btn-success bi bi-floppy" type="submit">
        Guardar
    </button>











}

<script src="~/Scripts/jquery-3.4.1.js"></script>

<link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
@section scripts{

    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    <script type="text/javascript">

    $(function () {
        $("#datepicker").datepicker({
            dateFormat: 'dd/mm/yy',
            changeMonth: true,
            changeYear: true,
            yearRange: '1910:2023',
            maxDate: new Date()
        });
    });





    function PreviewImagen(event) {
        var output = document.getElementById('imgUsuario');
        output.src = URL.createObjectURL(event.target.files[0]);
        output.onload = function () {
            URL.revokeObjectURL(output.src)
        }
    }

    function verificarPassword(controlId) {
        pass1 = document.getElementById('pass1');
        pass2 = document.getElementById('pass2');
        if (pass1.value != pass2.value) {
            pass1.style.borderColor = "red";
            pass2.style.borderColor = "red";
            $('#' + controlId).text("Las contraseñas no coinciden");
            $('#' + controlId).css({ "color": "red" })
            return false;
        }
        else
        {
            pass1.style.borderColor = "green";
            pass2.style.borderColor = "green";
            $('#' + controlId).text("Las contraseñas  coinciden");
            $('#' + controlId).css({ "color": "green" })
        }

    }

    function VerificarEmail(lblErrorEmail2) {
        pass1 = document.getElementById('txtEmail');
        pass2 = document.getElementById('txtEmail2');
        if (pass1.value != pass2.value) {
            pass1.style.borderColor = "red";
            pass2.style.borderColor = "red";
            $('#' + lblErrorEmail2).text("los email no coinciden");
            $('#' + lblErrorEmail2).css({ "color": "red" })
            return false;
        }
        else {
            pass1.style.borderColor = "green";
            pass2.style.borderColor = "green";
            $('#' + lblErrorEmail2).text("los email  coinciden");
            $('#' + lblErrorEmail2).css({ "color": "green" })
        }

    }






    function ValidarPass(event, controlId2) {
        var pass = document.getElementById("pass1").value;
        var lblError = document.getElementById("controlId2");
        lblError.innerHTML = "";
        var expt = /^(?=.*\d)(?=.*[\u0021-\u002b\u003c-\u0040])(?=.*[A-Z])(?=.*[a-z])\S{8,50}$/;
        if (!expt.test(pass)) {
            lblError.innerHTML = "la contraseña no es valido"
            lblError.style.color = "red";

            return false;
        }
        else {
            lblError.innerHTML = "la contraseña es valido";
            lblError.style.color = "green";

        }
    }

    //^\d{10}$

    function ValidarEmail(event, lblErrorEmail) {
        var email = document.getElementById("txtEmail").value;
        var lblError = document.getElementById("lblErrorEmail");
        lblError.innerHTML = "";
        var expt = /^([a-zA-z0-9_\.\-\+])+\@@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
        if (!expt.test(email)) {
            lblError.innerHTML = "El correo no es valido"
            lblError.style.color = "red";

            return false;
        }
        else {
            lblError.innerHTML = "El correo es valido";
            lblError.style.color = "green";

        }
    }

    function ValidarTelefono(event, lblErrorTelefono) {
        var telefono = document.getElementById("txtTelefono").value;
        var lblError = document.getElementById("lblErrorTelefono");
        lblError.innerHTML = "";
        var expt = /^\d{10}$/;
        if (!expt.test(telefono)) {
            lblError.innerHTML = "El telefono no es valido"
            lblError.style.color = "red";

            return false;
        }
        else {
            lblError.innerHTML = "El Telefono es valido";
            lblError.style.color = "green";

        }
    }

    function ValidarCelular(event, lblErrorCelular) {
        var telefono = document.getElementById("txtCelular").value;
        var lblError = document.getElementById("lblErrorCelular");
        lblError.innerHTML = "";
        var expt = /^\d{10}$/;
        if (!expt.test(telefono)) {
            lblError.innerHTML = "El Celular no es valido"
            lblError.style.color = "red";

            return false;
        }
        else {
            lblError.innerHTML = "El Celular es valido";
            lblError.style.color = "green";

        }
    }





    function SoloLetras1(event, controlIdnombre) {
        var letra = event.key;
        var regexOnlyLetters = /^[A-Za-z ]+$/;
        var lblError = document.getElementById("controlIdnombre");
        if (regexOnlyLetters.test(letra)) {
            lblError.innerHTML = "nombre valido";
            lblError.style.color = "green";
            return true;
        }
        else
        {
            lblError.innerHTML = "solo letras"
            lblError.style.color = "red";
            //alert('Solo se aceptn letras');
            return false;
        }
    }


    function SoloLetras2(event,controlID2) {
        var letra = event.key;
        var regexOnlyLetters = /^[A-Za-z ]+$/;
        var lblError = document.getElementById("controlID2");
        if (regexOnlyLetters.test(letra)) {
            lblError.innerHTML = "apellido paterno valido";
            lblError.style.color = "green";
            return true;
        }
        else {
            lblError.innerHTML = "solo letras";
            lblError.style.color = "red";

            alert('Solo se aceptn letras');
            return false;
        }
    }

    function SoloLetras3(event, controlId3) {
        var letra = event.key;
        var regexOnlyLetters = /^[A-Za-z ]+$/;
        var lblError = document.getElementById("controlId3");
        if (regexOnlyLetters.test(letra)) {
            lblError.innerHTML = "apellido materno valido"
            lblError.style.color = "green";
            return true;
        }
        else {
            lblError.innerHTML = "solo letras"
            lblError.style.color = "red";

            alert('Solo se aceptn letras');
            return false;
        }
    }




    $(document).ready(function () {
        $("#ddlPais").change(function () {
            $("#ddlEstado").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetEstado")',
                dataType: 'json',
                data: { IdPais: $("#ddlPais").val() },
                success: function (estados) {
                    $("#ddlEstado").append('<option value="0">' + 'Seleccione una opción' + '</option>');
                    $.each(estados, function (i, estados) {
                        $("#ddlEstado").append('<option value="'
                            + estados.IdEstado + '">'
                            + estados.Nombre + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed.' + ex);
                }
            });
        });
    });


    $(document).ready(function () {
        $("#ddlEstado").change(function () {
            $("#ddlMunicipio").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetMunicipio")',
                dataType: 'json',
                data: { IdEstado: $("#ddlEstado").val() },
                success: function (municipios) {
                    $("#ddlMunicipio").append('<option value="0">' + 'Seleccione una opción' + '</option>');
                    $.each(municipios, function (i, municipios) {
                        $("#ddlMunicipio").append('<option value="'
                            + municipios.IdMunicipio + '">'
                            + municipios.Nombre + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed.' + ex);
                }
            });
        });
    });


    $(document).ready(function () {
        $("#ddlMunicipio").change(function () {
            $("#ddlColonia").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetColonia")',
                dataType: 'json',
                data: { IdMunicipio: $("#ddlMunicipio").val() },
                success: function (colonias) {
                    $("#ddlColonia").append('<option value="0">' + 'Seleccione una opción' + '</option>');
                    $.each(colonias, function (i, colonias) {
                        $("#ddlColonia").append('<option value="'
                            + colonias.IdColonia + '">'
                            + colonias.Nombre + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed.' + ex);
                }
            });
        });
    });



    </script>

}

PL_MVC/Views/Dependiente/GetAll.cshtml
@model ML.Empleado

@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GetAll</h2>

<div class="row g-3">


    @foreach (ML.Empleado empleado in Model.Empleados)
    {

        <div class="card" style="width: 18rem;">

            <div class="card-body">
                <tr>
                    @if (empleado.Foto != null)
                    {
                        <img id="imgUsuario" src="data:image/jpeg;base64,@Convert.ToBase64String(empleado.Foto)" width="100" height="100" />
                    }
                    else
                    {
                        <img src="~/Image/DefaultImage.jpg" id="imgUsuario" width="100" height="100" />
                    }





                    <p class="card-text visually-hidden">@empleado.NumeroEmpleado</p>
                  
                    <p class="card-text">Nombre: @empleado.Nombre</p>
                    <p class="card-text">Apellido Paterno: @empleado.ApellidoPaterno</p>
                    <p class="card-text">Apellido Materno: @empleado.ApellidoMaterno</p>
                    
                    <p class="card-text">Empresa: @empleado.Empresa.Nombre</p>

                    <a class="btn btn-success bi bi-pencil" href="@Url.Action("GetByNumeroEmpleado", "Dependiente", new { numeroEmpleado = empleado.NumeroEmpleado })"></a>
                
                </tr>

            </div>
        </div>
    }



</div>

PL_MVC/Views/Dependiente/GetByNumeroEmpleado.cshtml
@model ML.Dependiente

@{
    ViewBag.Title = "GetByNumeroEmpleado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GetByNumeroEmpleado</h2>
<h2>@Model.Empleado.Nombre</h2>

@Html.ActionLink(" Agregar", "FormDependiente", "Dependiente", new { area = "" }, new { @class = "btn btn-success bi bi-person-plus" })

<table class="table table-bordered table-responsive">
    <thead>
        <tr>
            <td>Editar Dependiente</td>
            <td>IdDependiente</td>
            <td>NumeroEmpleado</td>

            <td>Nombre</td>
            <td>ApellidoPaterno</td>
            <td>ApellidoMaterno</td>
            <td>FechaNacimiento</td>
            <td>EstadoCivil</td>
            <td>Genero</td>
            <td>Telefono</td>
            <td>RFC</td>
            <td>IdDependiente</td>
            <td>IdDependienteTipo</td>
            <td>Tipo</td>

        </tr>
    </thead>


    <tbody>
        @foreach (ML.Dependiente dependiente in Model.Dependientes)
        {
            <tr>
                <td><a class="btn btn-warning bi bi-pencil" href="@Url.Action("FormDependiente", "Dependiente", new { IdDependiente = dependiente.IdDependiente })"></a></td>
                <td>@dependiente.IdDependiente</td>
                <td>@dependiente.Empleado.NumeroEmpleado</td>

                <td>@dependiente.Nombre</td>
                <td>@dependiente.ApellidoPaterno</td>
                <td>@dependiente.ApellidoMaterno</td>
                <td>@dependiente.FechaNacimiento</td>
                <td>@dependiente.EstadoCivil</td>
                <td>@dependiente.Genero</td>
                <td>@dependiente.Telefono</td>
                <td>@dependiente.RFC</td>
                <td>@dependiente.IdDependiente</td>
                <td>@dependiente.DependienteTipo.IdDependienteTipo</td>
                <td>@dependiente.DependienteTipo.Nombre</td>
                <td><a class="btn btn-danger bi bi-trash" href="@Url.Action("Delete", "Dependiente", new { IdDependiente= dependiente.IdDependiente})" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a></td>
            </tr>
        }
    </tbody>
</table>

PL_MVC/Views/Dependiente/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">


<div class="modal fade" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Aviso</h4>
            </div>
            <div class="modal-body">
                <p>@ViewBag.Mensaje</p>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "GetAll", "Empleado", new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal('show');
</script>